# Generated by Django 4.1.7 on 2023-07-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_attractions_booking_category_categoryhotel_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diy',
            name='attraction',
        ),
        migrations.AddField(
            model_name='diy',
            name='attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineering.attractions'),
        ),
    ]
