# Generated by Django 4.1.7 on 2023-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_remove_diy_attraction_diy_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryhotel',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
