# Generated by Django 4.1.7 on 2023-07-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_alter_categoryhotel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attraction', to='engineering.country'),
        ),
        migrations.RemoveField(
            model_name='diy',
            name='attraction',
        ),
        migrations.AddField(
            model_name='diy',
            name='attraction',
            field=models.ManyToManyField(to='engineering.attractions'),
        ),
    ]
